FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# b@@ks

API docs for b@@ks app team.

Collection list:

1. titles
2. books
3. bookshelfs
4. users
5. transactions

## Titles Collection [/titles]

### Get Titles by name [GET]

Api for search title by title name (in search page)

+ Request (application/json)

    {
        "title": "sample name",
        "categories": [
            "tech",
            "IT"
        ]
    }
        
    + Attributes
        + title: sample name (string, required) - String that point to title you want to search
        + categories: tech, IT (array[string], required) - List categories that related with title

+ Response 200 (application/json)

        {
            "results": [
                {
                    "title": "sample title 1",
                    "cover": "https://i.imgur.com/aylj7Xw.jpg",
                    "author": "sample author 1"
                },
                {
                    "title": "sample title 2",
                    "cover": "https://i.imgur.com/aylj7Xw.jpg",
                    "author": "sample author 2"
                }
            ]
        }
        
## Title Detail [/title/{id}]
### Get Title Detail [GET]

Api for getting title data from id

+ Request (application/json)

    {
        "id": 109
    }
        
    + Attributes
        + id: 101 (number, required) - Id that point to title you want to search

+ Response 200 (application/json)

        {
            "title": "sample title",
            "author": "J.K Rowling",
            "summary": "insert summary here",
            "categories": [
                "tech",
                "IT"
            ],
            "rating": 4.7,
            "reviews": [
                {
                    "username": "sample user",
                    "date": "1/1/2018",
                    "content": "sample content",
                    "rating": 4.0
                },
                {
                    "username": "sample user",
                    "content": "sample content",
                    "rating": 4.0
                }
            ],
            "books": [
                {
                    "image": "https://i.imgur.com/aylj7Xw.jpg",
                    "username": "sample user",
                    "date": "1/1/2018",
                    "status": "available"
                }
            ]
        }
        
## Available Books from Title [/title/{id}/available]
### Get Available Books of a Title [GET]

Api for getting available books from title id

+ Request (application/json)

    {
        "id": 109
    }
        
    + Attributes
        + id: 101 (number, required) - Id that point to title you want to search

+ Response 200 (application/json)

        {
            "results": [
                {
                    "book_id": "1",
                    "owner": "Owner A",
                    "image": "https://i.imgur.com/aylj7Xw.jpg",
                    "status": 1
                },
                {
                    "book_id": "2",
                    "owner": "Owner B",
                    "image": "https://i.imgur.com/aylj7Xw.jpg",
                    "status": 0
                }
            ]
        }