FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# b@@ks

API docs for b@@ks app team.

Collection list:

1. titles
2. books
3. bookshelfs
4. users
5. transactions

## Titles Collection [/books]

### Get Titles by name [GET]

Api for search title by title name (in search page)

+ Request (application/json)

    {
        "title": "sample name",
        "categories": [
            "tech",
            "IT"
        ]
    }
        
    + Attributes
        + title: sample name (string, required) - String that point to title you want to search
        + categories: tech, IT (array[string], required) - List categories that related with title

+ Response 200 (application/json)

        {
            "results": [
                {
                    "id": 101,
                    "title": "sample title 1",
                    "cover": "https://i.imgur.com/aylj7Xw.jpg",
                    "author": "sample author 1"
                },
                {
                    "id": 102
                    "title": "sample title 2",
                    "cover": "https://i.imgur.com/aylj7Xw.jpg",
                    "author": "sample author 2"
                }
            ]
        }
        
## Title Detail [/book/{id}]
### Get Title Detail [GET]

Api for search title by id (detail page)

+ Request (application/json)

    {
        "id": 109
    }
        
    + Attributes
        + id: 101 (number, required) - Id that point to title you want to search

+ Response 200 (application/json)

        {
            "title": "sample title",
            "author": "J.K Rowling",
            "summary": "insert summary here",
            "categories": [
                "tech",
                "IT"
            ],
            "rating": 4.7
        }